-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 10:36:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`surCategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`surCategorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`surCategorie` (
  `idSurCategorie` INT NOT NULL,
  `nomSurCategorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSurCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `idCategorie` INT NOT NULL,
  `nomCategorie` VARCHAR(45) NOT NULL,
  `idSurCategorie` INT NOT NULL,
  PRIMARY KEY (`idCategorie`),
  INDEX `surcategorie_idx` (`idSurCategorie` ASC) VISIBLE,
  CONSTRAINT `surcategorie`
    FOREIGN KEY (`idSurCategorie`)
    REFERENCES `mydb`.`surCategorie` (`idSurCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`annonce` ;

CREATE TABLE IF NOT EXISTS `mydb`.`annonce` (
  `idAnnonce` INT NOT NULL,
  `statut` TINYINT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `idCategorie` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idAnnonce`),
  INDEX `categorie_idx` (`idCategorie` ASC) VISIBLE,
  INDEX `user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `categorie`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `mydb`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `idPhoto` INT NOT NULL,
  `photo` TEXT NOT NULL,
  `idAnnonce` INT NOT NULL,
  PRIMARY KEY (`idPhoto`),
  INDEX `annonce_idx` (`idAnnonce` ASC) VISIBLE,
  CONSTRAINT `annonce`
    FOREIGN KEY (`idAnnonce`)
    REFERENCES `mydb`.`annonce` (`idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`critere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`critere` ;

CREATE TABLE IF NOT EXISTS `mydb`.`critere` (
  `idCritere` INT NOT NULL,
  `nomCritere` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `idCategorie` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCritere`),
  INDEX `categorie_idx` (`idCategorie` ASC) VISIBLE,
  CONSTRAINT `categorie`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `mydb`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valeurCritere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`valeurCritere` ;

CREATE TABLE IF NOT EXISTS `mydb`.`valeurCritere` (
  `idValeurCritere` INT NOT NULL,
  `valeur` VARCHAR(45) NOT NULL,
  `idAnnonce` INT NOT NULL,
  `idCritere` INT NOT NULL,
  PRIMARY KEY (`idValeurCritere`),
  INDEX `annonce_idx` (`idAnnonce` ASC) VISIBLE,
  INDEX `critere_idx` (`idCritere` ASC) VISIBLE,
  CONSTRAINT `annonce`
    FOREIGN KEY (`idAnnonce`)
    REFERENCES `mydb`.`annonce` (`idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `critere`
    FOREIGN KEY (`idCritere`)
    REFERENCES `mydb`.`critere` (`idCritere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
